[package]
name = "steamos-manager"
version = "24.3.0"
edition = "2021"

[profile.release]
strip="symbols"

[dependencies]
tokio = { version = "1", features = ["fs", "process", "io-std", "rt-multi-thread", "macros"] }
zbus = { version = "4", features = ["tokio"] }
